In [ ]:
import os

#get path to directory
os.chdir('/content/drive/MyDrive/Tcrdist3')

#get what's in the directory
contents = os.listdir()
print("Contents of the Google Drive directory:")
for item in contents:
    print(item)

Contents of the Google Drive directory:
raw_data.csv
dash_human.csv
dash2.csv
dash.csv
dash_beta_airr.csv
EBV_SARS_CoV_2_InfluenzaA_raw_data.tsv
EBV_SARS_CoV_2_InfluenzaA_raw_data.csv
project_one_work.ipynb


In [ ]:
#install tcrdist3
!pip install git+https://github.com/kmayerb/tcrdist3.git@0.2.2

  Cloning https://github.com/kmayerb/tcrdist3.git (to revision 0.2.2) to /tmp/pip-req-build-kw6gmwpo
  Running command git clone --filter=blob:none --quiet https://github.com/kmayerb/tcrdist3.git /tmp/pip-req-build-kw6gmwpo
  Running command git checkout -q 04b0b8c2573d04a9d2cb77f7a3aeeed3a0eab167
  Resolved https://github.com/kmayerb/tcrdist3.git to commit 04b0b8c2573d04a9d2cb77f7a3aeeed3a0eab167
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 45.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 438.1/438.1 kB 37.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.4/366.4 kB 33.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 14.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 478.0/478.0 kB 42.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.1/67.1 kB 9.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (se

In [60]:
import pandas as pd
#open tcrdist repertoire
from tcrdist.repertoire import TCRrep

#read .csv file needed to be utilized
df = pd.read_csv("EBV_SARS_CoV_2_InfluenzaA_raw_data.csv")

#determine what is going to be computed from the data
tr = TCRrep(cell_df = df,
            organism = 'human',
            chains = ['alpha'],
            db_file = 'alphabeta_gammadelta_db.tsv',
            compute_distances = False)

"""In this case, alpha sequences were selected in the VDJdb database and
so it needed to be determined on what to use. """

/usr/local/lib/python3.10/dist-packages/tcrdist/repertoire.py:500: UserWarning: nan gene was not recognized in reference db no cdr seq could be inferred
  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,
/usr/local/lib/python3.10/dist-packages/tcrdist/repertoire.py:504: UserWarning: nan gene was not recognized in reference db no cdr seq could be inferred
  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,
/usr/local/lib/python3.10/dist-packages/tcrdist/repertoire.py:508: UserWarning: nan gene was not recognized in reference db no cdr seq could be inferred
  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,
/usr/local/lib/python3.10/dist-packages/tcrdist/repertoire.py:190: UserWarning: Not all cells/sequences could be grouped into clones.220 of 2520 were not captured. This occurs when any of the values in the index columns are null or missing for a given sequence. To see entries with missing values use: tcrdist.repertoire.TCRrep._show_incomplete()
  self.dedu

'In this case, alpha sequences were selected in the VDJdb database and \nso it needed to be determined on what to use. '

In [61]:
#define the amount of CPU cores to carry out the computations
tr.cpus = 4

In [62]:
#define and compute the distances between the data
tr.compute_sparse_rect_distances(radius = 50, chunk_size = 100)

  0%|          | 0/255 [00:00<?, ?it/s]

In [63]:
#check if the data has been calculated and converted into a sparse matrix
tr.rw_alpha

<25436x25436 sparse matrix of type '<class 'numpy.int16'>'
	with 3086668 stored elements in Compressed Sparse Row format>

In [ ]:
print(tr.rw_alpha)

  (0, 0)	-1
  (0, 2344)	48
  (0, 2404)	48
  (0, 2432)	48
  (0, 11829)	45
  (0, 15025)	45
  (0, 15477)	48
  (1, 1)	-1
  (1, 177)	47
  (1, 1629)	47
  (1, 1813)	-1
  (1, 2177)	36
  (1, 2262)	36
  (1, 2398)	36
  (1, 2431)	48
  (1, 2450)	48
  (1, 2611)	9
  (1, 7003)	24
  (1, 9028)	50
  (1, 9335)	33
  (1, 13432)	36
  (1, 14812)	44
  (1, 15154)	36
  (1, 15694)	33
  (1, 17558)	33
  :	:
  (25434, 25384)	-1
  (25434, 25386)	24
  (25434, 25388)	6
  (25434, 25390)	-1
  (25434, 25392)	12
  (25434, 25394)	12
  (25434, 25396)	-1
  (25434, 25398)	-1
  (25434, 25400)	6
  (25434, 25402)	-1
  (25434, 25404)	6
  (25434, 25406)	12
  (25434, 25408)	12
  (25434, 25410)	6
  (25434, 25412)	-1
  (25434, 25420)	6
  (25434, 25424)	6
  (25434, 25426)	24
  (25434, 25428)	-1
  (25434, 25430)	-1
  (25434, 25432)	-1
  (25434, 25434)	-1
  (25435, 14669)	46
  (25435, 21749)	48
  (25435, 25435)	-1


In [ ]:
from scipy import sparse

In [64]:
#define what is the sparse matrix
sparse_matrix = tr.rw_alpha

In [65]:
#save the sparse matrix as a .npz file
sparse.save_npz("sparse_matrix", sparse_matrix)

In [66]:
#convert the .npz file to a dense array
dense_array = sparse_matrix.toarray()

In [ ]:
print(dense_array)

[[-1  0  0 ...  0  0  0]
 [ 0 -1  0 ...  0  0  0]
 [ 0  0 -1 ...  0  0  0]
 ...
 [ 0  0  0 ... -1  0  0]
 [ 0  0  0 ...  0 -1  0]
 [ 0  0  0 ...  0  0 -1]]
